version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 80:5000
    volumes:
      - /srv/bmswens/submissions:/app/submissions
      - /srv/bmswens/db:/app/db
      - /srv/bmswens/truth:/app/truth

  eval:
    build: ./eval
    volumes:
      - /srv/bmswens/submissions:/app/submissions
      - /srv/bmswens/db:/app/db
      - /srv/bmswens/truth:/app/truth
      - /afs/csail.mit.edu/u/b/bmswens/Rainforest-Challenge-Submission/eval/token.json:/app/token.json
      - /afs/csail.mit.edu/u/b/bmswens/Rainforest-Challenge-Submission/eval/credentials.json:/app/credentials.json
