version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:5000
    volumes:
      - /srv/bmswens/submissions:/app/submissions
      - /srv/bmswens/db:/app/db
      - /srv/bmswens/truth:/app/truth

  eval:
    build: ./eval
    volumes:
      - /srv/bmswens/submissions:/app/submissions
      - /srv/bmswens/db:/app/db
      - /srv/bmswens/truth:/app/truth
    
